### DISCUSSION TITLE
mqtt message resend (periodic)

### DISCUSSION THREAD

**Discussion by adnet-solutions** [bassmaster187/TeslaLogger#967] [General]
Hi,
kann man den teslalogger irgendwie dazu bringen die Messages die jetzt per MQTT versendet werden periodic also zum Beispiel alle 20sec zu schicken und nicht nur beim Update?
Ich habe das Problem das mein IOBroker die Messages abonniert hat und diese dann auf Alias Datenpunkte verteilt.
Nun ist das Issue wen ich den IOBroker starte und das Auto gerade schläft bekommt der IOBroker keine neues MQTT Topic und der MQTT Datenpunkzt bleibt "NULL". Damit kommt der Alias Adapter aber nicht wirklich klar und crasht. 
Auch der EVCC zur Ladesteuerung erwartet ein regelmässiges Update auf die Batteriekapaziät um zu sehen das System Alive ist.
Daher wäre es gut wenn man zum Beiepiel alle 20 sekunden das MQTT Topic resenden könnte.
Oder ist das gar schon möglich?

Wenn ich MQTT richtig verstanden habe könte man ggf die Messages auch mit dem Retain Flag versehen dann würde zumindest das Issue mit dem IOBroker nicht mehr auftreten da er dann immer die letzte Message nochmal bekommen würde vom Broker. Das muss aber wohl auch beim Teslaloger beim Publishen gesetzt werden.

**Comment by HGSiegel** [comment]
Hallo, 
mir geht es genauso! Ich möchte die MQTT-Daten nutzen, um die Tesla API nicht (so oft) aufzurufen, da das meine alten Teslas gelegentlich aufweckt. Es wäre sehr hilfreich, wenn man entweder die Frequenz der Nachrichten selbst bestimmen könnte, oder Nachrichten bei Wertänderung immer sofort versendet werden, die dann beim Subscriber auch sehr zeitnah ankommen. So könnte man in der Regel auf die eigene Verwendung des Tesla-API verzichten...

Gibt es solche Einstellungen im Teslalogger vielleicht schon und wenn ja, wie nutze ich sie? Anderenfalls wäre ein entsprechendes Update super willkommen!

**Comment by Adminius** [comment]
Ich nutze selbst EVCC habe kein einziges Problem in Verbindung mit TeslaLogger/MQTT.
Man kann Timeout einstellen. So stehts bei mir:

```
- name: ev3
    type: custom
    title: Tsla 3ph
    capacity: 77 # battery capacity (kWh)
    phases: 3
    soc: # battery soc (%)
      source: mqtt
      topic: teslalogger/car/3/battery_level
      timeout: 720h # 30d
    range:
      source: mqtt
      topic: teslalogger/car/3/battery_range_km
      timeout: 720h
    odometer:
      source: mqtt
      topic: teslalogger/car/3/odometer
      timeout: 720h
```
