### ISSUE TITLE
docker-compose.yml Database Volume missing

### ISSUE THREAD

**Issue by 5hay** [bassmaster187/TeslaLogger#588]
**Describe the bug**
The docker-compose.yml file needs a persistent volume for the data of the mariadb service. Otherwise all the data will be gone after a restart of the container.

**To Reproduce**
* Use the app with Docker + docker-compose
* Add data
* Restart containers
* Data will be reset

**Expected behavior**
Data should be persistent.

** Teslalogger Type **
Docker

** Do you use Tasker or iBeacon **
No

**Additional context**
The fix is quite easy.

```yaml
  database:
    image: mariadb:10.4.7
    restart: always
    env_file:
      - .env
    volumes:
      - ./TeslaLogger/sqlschema.sql:/docker-entrypoint-initdb.d/sqlschema.sql
      - ./mariadb:/var/lib/mysql # you could also let Docker handle that volume for you, but it is required so the data is persistent
    ports:
      - 10102:3306
    environment:
      - TZ=Europe/Berlin
```
