### ISSUE TITLE
Health Check Support for Docker

### ISSUE THREAD

**Issue by dehsgr** [bassmaster187/TeslaLogger#837]
Running TeslaLogger as Docker Container and managing it through e.g. Protainer TeslaLogger Containers show only as running. There  is a Feature to support Health Check, e.g. curl'ing an API URL, checking MySQL Status, ... 

It would be nice if we get it implemented in containers. A small Sample from another Container is:
```
healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/getStatus"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
```

A possible Health Check for DB Container would be:
```
healthcheck:
      test: "/usr/bin/mysql --user=teslalogger --password=teslalogger --execute \"SHOW DATABASES;\""
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
```

A possible Health Check for Webserver Container would be:
```
healthcheck:
      test: curl -f -u <AdminUser>:<AdminPass> http://localhost/admin/current_json.php || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
```

More Information are available here:
- https://docs.docker.com/engine/reference/run/#healthcheck
